# Generated by Django 4.2.7 on 2023-11-28 20:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['brand_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the category of the UAV', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('weight', models.CharField(help_text='The weight of the UAV', max_length=100, verbose_name='Weight')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='rental.brand')),
                ('category', models.ManyToManyField(help_text='Select the category for this UAV', to='rental.category')),
            ],
        ),
        migrations.CreateModel(
            name='UavInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='THe unique ID for the rental UAV', primary_key=True, serialize=False)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('r', 'Rented'), ('a', 'Available')], default='m', help_text='UAV availability', max_length=1)),
                ('Uav', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='rental.uav')),
            ],
            options={
                'ordering': ['return_date'],
            },
        ),
    ]
